import 'package:equatable/equatable.dart';

import '../../../domain/models/project.dart';
import '../../../domain/models/task.dart';
import '../../../domain/models/user.dart';

enum BoardStatus { urgent, running, ongoing }

class AddTaskFormModel extends Equatable {
  final String taskName;
  final Project? selectedProject;
  final String description;
  final List<User> selectedMembers;
  final DateTime? selectedDate;
  final String startTime;
  final String endTime;
  final BoardStatus boardStatus;

  const AddTaskFormModel({
    this.taskName = '',
    this.selectedProject,
    this.description = '',
    this.selectedMembers = const [],
    this.selectedDate,
    this.startTime = '',
    this.endTime = '',
    this.boardStatus = BoardStatus.running,
  });

  AddTaskFormModel copyWith({
    String? taskName,
    Project? selectedProject,
    String? description,
    List<User>? selectedMembers,
    DateTime? selectedDate,
    String? startTime,
    String? endTime,
    BoardStatus? boardStatus,
  }) {
    return AddTaskFormModel(
      taskName: taskName ?? this.taskName,
      selectedProject: selectedProject ?? this.selectedProject,
      description: description ?? this.description,
      selectedMembers: selectedMembers ?? this.selectedMembers,
      selectedDate: selectedDate ?? this.selectedDate,
      startTime: startTime ?? this.startTime,
      endTime: endTime ?? this.endTime,
      boardStatus: boardStatus ?? this.boardStatus,
    );
  }

  @override
  List<Object?> get props => [
    taskName,
    selectedProject,
    description,
    selectedMembers,
    selectedDate,
    startTime,
    endTime,
    boardStatus,
  ];

  Task toTask() {
    final now = DateTime.now();
    return Task(
      id: '', // Will be generated by repository
      title: taskName,
      description: description,
      status: _mapBoardStatusToTaskStatus(boardStatus),
      priority: _mapBoardStatusToTaskPriority(boardStatus),
      projectId: selectedProject?.id ?? '',
      assigneeId: selectedMembers.isNotEmpty ? selectedMembers.first.id : null,
      dueDate: selectedDate,
      createdAt: now,
      updatedAt: now,
    );
  }

  TaskStatus _mapBoardStatusToTaskStatus(BoardStatus boardStatus) {
    switch (boardStatus) {
      case BoardStatus.urgent:
        return TaskStatus.todo;
      case BoardStatus.running:
        return TaskStatus.inProgress;
      case BoardStatus.ongoing:
        return TaskStatus.inProgress;
    }
  }

  TaskPriority _mapBoardStatusToTaskPriority(BoardStatus boardStatus) {
    switch (boardStatus) {
      case BoardStatus.urgent:
        return TaskPriority.urgent;
      case BoardStatus.running:
        return TaskPriority.high;
      case BoardStatus.ongoing:
        return TaskPriority.medium;
    }
  }
}